// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment-method.proto

package com_ta04_srv_payment_method

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentMethod struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccountNumber        string   `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountHolderName    string   `protobuf:"bytes,4,opt,name=account_holder_name,json=accountHolderName,proto3" json:"account_holder_name,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethod) Reset()         { *m = PaymentMethod{} }
func (m *PaymentMethod) String() string { return proto.CompactTextString(m) }
func (*PaymentMethod) ProtoMessage()    {}
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a487cb9e3da1e3, []int{0}
}

func (m *PaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethod.Unmarshal(m, b)
}
func (m *PaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethod.Marshal(b, m, deterministic)
}
func (m *PaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethod.Merge(m, src)
}
func (m *PaymentMethod) XXX_Size() int {
	return xxx_messageInfo_PaymentMethod.Size(m)
}
func (m *PaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethod proto.InternalMessageInfo

func (m *PaymentMethod) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PaymentMethod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentMethod) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *PaymentMethod) GetAccountHolderName() string {
	if m != nil {
		return m.AccountHolderName
	}
	return ""
}

func (m *PaymentMethod) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type IndexPaymentMethodsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexPaymentMethodsRequest) Reset()         { *m = IndexPaymentMethodsRequest{} }
func (m *IndexPaymentMethodsRequest) String() string { return proto.CompactTextString(m) }
func (*IndexPaymentMethodsRequest) ProtoMessage()    {}
func (*IndexPaymentMethodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a487cb9e3da1e3, []int{1}
}

func (m *IndexPaymentMethodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexPaymentMethodsRequest.Unmarshal(m, b)
}
func (m *IndexPaymentMethodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexPaymentMethodsRequest.Marshal(b, m, deterministic)
}
func (m *IndexPaymentMethodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexPaymentMethodsRequest.Merge(m, src)
}
func (m *IndexPaymentMethodsRequest) XXX_Size() int {
	return xxx_messageInfo_IndexPaymentMethodsRequest.Size(m)
}
func (m *IndexPaymentMethodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexPaymentMethodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexPaymentMethodsRequest proto.InternalMessageInfo

type GetAllPaymentMethodRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllPaymentMethodRequest) Reset()         { *m = GetAllPaymentMethodRequest{} }
func (m *GetAllPaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllPaymentMethodRequest) ProtoMessage()    {}
func (*GetAllPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a487cb9e3da1e3, []int{2}
}

func (m *GetAllPaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPaymentMethodRequest.Unmarshal(m, b)
}
func (m *GetAllPaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *GetAllPaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPaymentMethodRequest.Merge(m, src)
}
func (m *GetAllPaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllPaymentMethodRequest.Size(m)
}
func (m *GetAllPaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPaymentMethodRequest proto.InternalMessageInfo

func (m *GetAllPaymentMethodRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *GetAllPaymentMethodRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetOnePaymentMethodRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOnePaymentMethodRequest) Reset()         { *m = GetOnePaymentMethodRequest{} }
func (m *GetOnePaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*GetOnePaymentMethodRequest) ProtoMessage()    {}
func (*GetOnePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a487cb9e3da1e3, []int{3}
}

func (m *GetOnePaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOnePaymentMethodRequest.Unmarshal(m, b)
}
func (m *GetOnePaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOnePaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *GetOnePaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOnePaymentMethodRequest.Merge(m, src)
}
func (m *GetOnePaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_GetOnePaymentMethodRequest.Size(m)
}
func (m *GetOnePaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOnePaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOnePaymentMethodRequest proto.InternalMessageInfo

func (m *GetOnePaymentMethodRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Response struct {
	PaymentMethod        *PaymentMethod   `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Error                *Error           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	PaymentMethods       []*PaymentMethod `protobuf:"bytes,3,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a487cb9e3da1e3, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPaymentMethod() *PaymentMethod {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetPaymentMethods() []*PaymentMethod {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a487cb9e3da1e3, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PaymentMethod)(nil), "com.ta04.srv.payment.method.PaymentMethod")
	proto.RegisterType((*IndexPaymentMethodsRequest)(nil), "com.ta04.srv.payment.method.IndexPaymentMethodsRequest")
	proto.RegisterType((*GetAllPaymentMethodRequest)(nil), "com.ta04.srv.payment.method.GetAllPaymentMethodRequest")
	proto.RegisterType((*GetOnePaymentMethodRequest)(nil), "com.ta04.srv.payment.method.GetOnePaymentMethodRequest")
	proto.RegisterType((*Response)(nil), "com.ta04.srv.payment.method.Response")
	proto.RegisterType((*Error)(nil), "com.ta04.srv.payment.method.Error")
}

func init() { proto.RegisterFile("payment-method.proto", fileDescriptor_75a487cb9e3da1e3) }

var fileDescriptor_75a487cb9e3da1e3 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xdd, 0xca, 0xd3, 0x40,
	0x10, 0x35, 0x69, 0x53, 0xed, 0x94, 0x46, 0xba, 0x0d, 0x12, 0xaa, 0x17, 0x25, 0x50, 0x28, 0xa2,
	0x8b, 0x54, 0x45, 0x6f, 0x05, 0xc5, 0x1f, 0xb0, 0x6a, 0x82, 0xd7, 0x25, 0x4d, 0x06, 0x13, 0x6d,
	0xb2, 0xe9, 0xee, 0xa6, 0xb5, 0xaf, 0xe3, 0x7b, 0xf8, 0x46, 0x3e, 0x84, 0x74, 0x93, 0x80, 0x2b,
	0xfd, 0xc2, 0xd7, 0x8b, 0xaf, 0x77, 0xbb, 0x33, 0x67, 0xcf, 0x39, 0x39, 0x33, 0x04, 0x9c, 0x22,
	0x3c, 0x64, 0x98, 0xcb, 0xc7, 0x19, 0xca, 0x84, 0xc5, 0xb4, 0xe0, 0x4c, 0x32, 0x72, 0x3f, 0x62,
	0x19, 0x95, 0xe1, 0x93, 0x67, 0x54, 0xf0, 0x1d, 0xad, 0x21, 0xb4, 0x82, 0x78, 0xbf, 0x0c, 0x18,
	0x7e, 0xae, 0x4a, 0x1f, 0x55, 0x85, 0xd8, 0x60, 0xa6, 0xb1, 0x6b, 0x4c, 0x8d, 0xb9, 0xe5, 0x9b,
	0x69, 0x4c, 0x08, 0x74, 0xf3, 0x30, 0x43, 0xd7, 0x9c, 0x1a, 0xf3, 0xbe, 0xaf, 0xce, 0x64, 0x06,
	0x76, 0x18, 0x45, 0xac, 0xcc, 0xe5, 0x2a, 0x2f, 0xb3, 0x35, 0x72, 0xb7, 0xa3, 0xba, 0xc3, 0xba,
	0xba, 0x54, 0x45, 0x42, 0x61, 0xdc, 0xc0, 0x12, 0xb6, 0x89, 0x91, 0xaf, 0x14, 0x53, 0x57, 0x61,
	0x47, 0x75, 0xeb, 0x9d, 0xea, 0x2c, 0x8f, 0xb4, 0xf7, 0xa0, 0x27, 0x64, 0x28, 0x4b, 0xe1, 0x5a,
	0x0a, 0x52, 0xdf, 0xbc, 0x07, 0x30, 0x79, 0x9f, 0xc7, 0xf8, 0x53, 0x33, 0x2a, 0x7c, 0xdc, 0x96,
	0x28, 0xa4, 0xf7, 0x01, 0x26, 0x6f, 0x51, 0xbe, 0xda, 0x6c, 0xb4, 0x76, 0xdd, 0x25, 0x0e, 0x58,
	0xdb, 0x12, 0xf9, 0x41, 0x7d, 0x51, 0xdf, 0xaf, 0x2e, 0xff, 0x28, 0x99, 0x9a, 0xd2, 0x23, 0xc5,
	0xf5, 0x29, 0xc7, 0x93, 0x5c, 0xff, 0x45, 0xe3, 0xfd, 0x31, 0xe0, 0x8e, 0x8f, 0xa2, 0x60, 0xb9,
	0x40, 0xf2, 0x05, 0xec, 0x3a, 0xdb, 0x55, 0x95, 0xad, 0x02, 0x0e, 0x16, 0x0f, 0x69, 0x4b, 0xfe,
	0x54, 0xd7, 0x19, 0x16, 0xda, 0x28, 0x5e, 0x82, 0x85, 0x9c, 0x33, 0xae, 0x4c, 0x0e, 0x16, 0x5e,
	0x2b, 0xd3, 0x9b, 0x23, 0xd2, 0xaf, 0x1e, 0x90, 0x00, 0xee, 0xea, 0x66, 0x84, 0xdb, 0x99, 0x76,
	0xce, 0x74, 0x63, 0x6b, 0x6e, 0x84, 0xf7, 0x1c, 0x2c, 0x25, 0x72, 0x5c, 0x89, 0x88, 0xc5, 0x58,
	0x47, 0xaa, 0xce, 0xc4, 0x85, 0xdb, 0x19, 0x0a, 0x11, 0x7e, 0x6b, 0x36, 0xa5, 0xb9, 0x2e, 0x7e,
	0x77, 0xc1, 0xd1, 0x88, 0x03, 0xe4, 0xbb, 0x34, 0x42, 0xb2, 0x87, 0xf1, 0x89, 0xb1, 0x92, 0x17,
	0xad, 0x16, 0xaf, 0x5e, 0x84, 0xc9, 0xac, 0xf5, 0x61, 0x33, 0x28, 0xef, 0x16, 0x49, 0x60, 0x14,
	0x24, 0x6c, 0xaf, 0xef, 0xfd, 0x19, 0xc9, 0x5c, 0x5f, 0x29, 0x05, 0x12, 0x48, 0xc6, 0xf1, 0x02,
	0x52, 0xdf, 0x61, 0xfc, 0xb5, 0x88, 0x43, 0x79, 0x09, 0xad, 0x1f, 0xe0, 0xbc, 0x46, 0x21, 0x39,
	0x3b, 0xdc, 0xbc, 0xd8, 0xba, 0xa7, 0x7e, 0x63, 0x4f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x09,
	0xea, 0x5a, 0x15, 0xde, 0x04, 0x00, 0x00,
}
